-- Sample data for testing (optional)
-- Note: This file is for reference only. Actual face embeddings will be generated by the Python service.

USE attendance_db;

-- Example: Insert a sample employee (you would normally register through the API)
-- The face_embedding would be a JSON array of 128 float values from face_recognition library
-- This is just a placeholder structure

-- Uncomment and modify if you want to insert test data manually:
/*
INSERT INTO employees (emp_code, name, face_embedding) VALUES 
('EMP001', 'John Doe', '[]'),
('EMP002', 'Jane Smith', '[]');
*/
